//---

localizationModule.constant('StiDictionary', {
  toEnglish: {
	  	'Стажёр':'Intern',
        'Имя':'Name',
	  	'Фамилия': 'Last Name',
 		'Отчество':'Middle name',
        'Город':'City',
		'Университет':'University',
		'Телефон':'Telephone',
		'Резюме':'Resume',
		'Согласен получать на email предложения о вакансиях и обучении':'I agree to receive offers by email about vacancies and training',
		'Уровень английского':'English level',
		'Опыт Cache':'Experience Cache',
		'Опыт DeepSee':'Experience DeepSee',
		'Опыт Ensemble':'Experience Ensemble',
		'Оценка TET':'Evaluation of TET',
		'Оценка PET':'Evaluation of PET',
		'Полное название':'Full name',
		'Аббревиатура':'Abbreviation',
		'Адрес университета':'Address of the University',
		'Web-страница':'Web-page',
		'Куратор':'Curator',
		'Доп. контакты':'Extras. contact information',
		'Система стажёров и вузов академической программы':'System interns and universities academic program',
		'Информация':'Information',
		'Кафедра':'Chair',
		'Факультет':'Faculty',
		'Стажёры':'Interns',
		'Университеты':'Universities',
		'Место обучения' : 'Location of study',
		'Адрес' : 'Address',
		'Аудитория' : 'Classroom',
		'Стажировки' : 'Internships',
		'Название стажировки' : 'Name of internship',
		'Компания' : 'Company',
		'Дата начала' : 'Date of start',
		'Дата окончания' : 'Date of end',
		'Количество свободных мест' : 'Number of seats',
		'Заявки' : 'Applications',
		'Максимальное количество учеников' : 'Maximum number of students',
		'Стажировка' : 'Internship',
        'Страна' : 'Country',
        'Дата рождения' : 'Birthday',
        'Компании' : 'Companies',
		'Язык системы' : 'Language of system',
		'Администратор' : 'Administrator',
		'Выход' : 'Log out',
		'Телефон куратора' : 'Curator phone ',
		'Email куратора' : 'Curator email',
		'Количество стажёров' : 'Number of interns',
		'Статус' : 'Status',
		'Система стажёров' : 'The system of interns',
		'Контактное лицо' : 'Contact person',
		'Регион' : 'Region',
		'Размер страницы' : 'Page size',
		'Гость' : 'Guest',
        'Вход' : 'Log in',
        'Создать заявку' : '',
        'Город, Регион, Страна' : 'City, State, Сountry',
		'Поиск' : 'Search',
		'Оформление заявки на стажировку' : 'Making an application for an internship',
		'Добавление стажёра' : 'Add intern',
		'Создать заявку' : 'Create application',
		'Страница' : 'Page',
		'Следующая страница' : 'Next page',
		'Последняя страница' : 'Last page',
		'Первая страница' : 'First page',
		'Предыдущая страница' : '',
		'Добавить' : 'Add',
		'Выберите университет для отображения полной информации.' : 'Select University to show information.',
		'Изменить' : 'Change',
		'Удалить' : 'Delete',
		'Предыдущая страница' : 'Previous page',
		'Режим' : 'Mode',
		'Добавление университета' : 'Adding University',
		'Основная информация' : 'General information',
		'Электронный адрес' : 'Email',
		'Готово!' : 'Finish!',
        'Университет добавлен.' : 'University is added.',
        'Редактирование университета' : 'Edit University',
		'Сохранить' : 'Save',
		'Изменения сохранены.' : 'Changes are saved.',
		'Внимание!' : 'Warning!',
		'Университет удален.' : 'University deleted.',
		'Выберите компанию для отображения полной информации.' : 'Choose a company to show information.',
		'Добавление компании' : 'Adding companies',
		'Адрес компании' : 'Company address',
		'Компания добавлена.' : 'Company is added.',
		'Компания удалена.' : 'Company is deleted.',
		'Редактирование компании' : 'Edit company',
		'Выберите стажёра для отображения полной информации.' : 'Select a intern to show information.',
		'Редактирование стажёра' : 'Edit intern',
		'Добавление стажёра' : 'Adding intern',
		'Стажёр добавлен.' : 'Intern is added.',
		'Стажёр удален.' : 'Intern is deleted.',
		'Выберите стажировку для отображения полной информации.' : 'Select internship to show information.',
		'Добавление стажировки' : 'Adding internship',
		'Активна' : 'Active',
		'Стажировка добавлена.' : 'Internship is added',
		'Редактирование стажировки' : 'Edit internship',
		'Стажировка удалена.' : 'Internsip is deleted.',
		'Принять заявку' : 'Accept the application',
		'Выберите заявку для отображения полной информации' : 'Select the application to show full information',
		'Создание заявки' : 'Create application',
		'Заявка принята' : 'Application is added',
		'Принять стажёра' : 'Add intern',
		'Заявка удалена.' : 'Application is deleted.',
		'Отмена' : 'Cancel',
		'Очистить' : 'Clean',
		'Выберите ваш университет' : 'Select your university',
		'Выберите стажировку' : 'Select internship',
		'Выберите компанию' : 'Select company',
		'Стажёр с таким именем/фамилией/датой рождения есть! Изменить старую запись или добавить нового стажёра?' : 'Intern by that name / last name / date of birth exists! Change the old record or add a new intern?',
		'Сотрудники' : 'Employees',
		'Редактирование сотрудника' : 'Edit employee',
		'Добавление сотрудника' : 'Add the employee',
		'ФИО' : 'L,F,M name',
		'Редактировать' : 'Edit',
		'Фамилия или email' : 'Type LastName or email',
		'Фамилия И.О., Email, Организация' : 'LastName, Email',
		'Заменить' : 'Replace',
		'Рассылка' : 'Subscribe',
	 	'Не активна' : 'No active',
	 	'Активна' : 'Active',
	 	'Не оформлена' : 'No',
	    'Оформлена' : 'Yes',
	    'Введите полное название университета' : 'Enter the full name of the university',
	    'Выбрать' : 'Select',
		'Университета, указанного в заявке, нет в базе данных! Добавить его или выбрать другой университет из списка?' : 'University of the application is not in the database! Add it or select another university from the list?',
	 	'Вставьте url на резюме онлайн или в pdf на сетевом диске' : 'Insert the url on a resume online or on a network drive pdf ',
	 	'Добавление стажера' : 'Add intern',
		'Принять стажера' : 'Accept intern',
		'Удалить данную запись?' : 'Delete this record?',
		'Комментарий#1' : 'Comments1',
		'Комментарий#2' : 'Comments2',
		'Группы рассылки' : 'Mailing groups',
  },
  toRussian: {
  },
  getTranslate: function(word, toLanguage){
	var def = function(key){
		console.log("'" + key + "' : '',");
		
		return key;	
	};  
	 
		  
    switch(toLanguage){
        case 'en':
            return this.toEnglish[word] ? this.toEnglish[word] : def(word);

    }
    
    return word;
  }
});
